### ISSUE TITLE
Reel dont work

### ISSUE THREAD

**Issue by Pejmandev** [Masterolic/Insta-Downloader#1]
Reel dont work semes 
Iwant use your code in my python app and dont work for reel but post code working nice

**Comment by Masterolic** [comment]
Hello! Reel works but In certain reels it download thumbnail instead of video issue with the api need to find alternative

**Comment by Masterolic** [comment]
Hey @Pejmandev we have updated repo which fixes your issues please check

**Comment by Lo-pro-file** [comment]
Reel work fine ❤️❤️ YouTube Download problem

**Comment by Masterolic** [comment]
@Lo-pro-file good... The YouTube Problem is not ours maybe you are using a shared ip address or YouTube is blocking your ip address..use proxy for avoiding
